/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetobentech01.views;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import projetobentech01.conexao.Conexao;
import projetobentech01.model.CadastroCliente;

/**
 *
 * @author p772920
 */
public class FrmMostrarCadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form FrmMostrarCadastroCliente
     */
    public FrmMostrarCadastroCliente() {
        initComponents();
        
        // modificar cabeçalho Jtabel
        JTableHeader jth = jtableCadastroCliente.getTableHeader();
        jth.setBackground(new Color(51,51,51));
        jth.setForeground(Color.WHITE);
        jth.setFont(new Font("Century Gothic", Font.BOLD, 18));
        jtableCadastroCliente.setRowHeight(18);
    }
    private Connection conn = null;
    
    // metodo para preechimento da jtablecadastroCliente
    // buscando do banco de dados
    public void preecheerJtable(String sql){
        conn = Conexao.getConnection();
        
        try {
            PreparedStatement stmt = conn.prepareCall(sql);
            stmt.execute();
            
            ResultSet rs = stmt.executeQuery();
            DefaultTableModel model = (DefaultTableModel) jtableCadastroCliente.getModel();
            model.setNumRows(0);//para inicializar do primeiro elemento da tabela
            
            // tratamento de data
            
            DateFormat data = new SimpleDateFormat("dd/MM/yyyy");
            
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("codigo_cliente"),
                    rs.getString("nome"),
                    rs.getString("sobrenome"),
                    rs.getInt("idade"),
                    rs.getString("CPF"),
                    data.format(rs.getDate("data_nascimento")),
                    rs.getString("sexo"),
                    rs.getInt("id_tb_cadastro")
                });
            }
        Conexao.fecharConexao(conn, stmt, rs);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possivel carregar dados de clientes cadastrados do banco\nErro: " + ex);
        }

    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableCadastroCliente = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPesquisaNome = new javax.swing.JTextField();
        txtPesquisaCPF = new javax.swing.JTextField();
        btnAtualizar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();
        txtNControle = new javax.swing.JTextField();
        txtNomeControle = new javax.swing.JTextField();
        lblFechar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clientes Cadastrados");
        setMaximumSize(new java.awt.Dimension(1250, 600));
        setMinimumSize(new java.awt.Dimension(1250, 600));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, null));
        jPanel1.setMaximumSize(new java.awt.Dimension(900, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(900, 600));
        jPanel1.setName(""); // NOI18N

        jtableCadastroCliente.setBackground(new java.awt.Color(51, 51, 51));
        jtableCadastroCliente.setForeground(new java.awt.Color(255, 255, 255));
        jtableCadastroCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Sobrenome", "Idade", "CPF", "Data Nascimento", "Sexo", "n° de controle"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableCadastroCliente.setSelectionBackground(new java.awt.Color(102, 153, 255));
        jtableCadastroCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableCadastroClienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableCadastroCliente);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 153, 255));
        jLabel3.setText("Pesquisa por Nome");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 153, 255));
        jLabel4.setText("Pesquisa por CPF");

        txtPesquisaNome.setBackground(new java.awt.Color(153, 153, 153));
        txtPesquisaNome.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtPesquisaNome.setForeground(new java.awt.Color(255, 255, 255));
        txtPesquisaNome.setBorder(null);
        txtPesquisaNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesquisaNomeKeyTyped(evt);
            }
        });

        txtPesquisaCPF.setBackground(new java.awt.Color(153, 153, 153));
        txtPesquisaCPF.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtPesquisaCPF.setForeground(new java.awt.Color(255, 255, 255));
        txtPesquisaCPF.setBorder(null);
        txtPesquisaCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPesquisaCPFKeyTyped(evt);
            }
        });

        btnAtualizar.setBackground(new java.awt.Color(102, 153, 255));
        btnAtualizar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnAtualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setBorder(null);
        btnAtualizar.setFocusable(false);
        btnAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAtualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAtualizarMouseExited(evt);
            }
        });
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnDeletar.setBackground(new java.awt.Color(102, 153, 255));
        btnDeletar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        btnDeletar.setForeground(new java.awt.Color(255, 255, 255));
        btnDeletar.setText("Deletar");
        btnDeletar.setBorder(null);
        btnDeletar.setFocusable(false);
        btnDeletar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeletarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeletarMouseExited(evt);
            }
        });
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        txtNControle.setBackground(new java.awt.Color(153, 153, 153));
        txtNControle.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtNControle.setForeground(new java.awt.Color(255, 255, 255));
        txtNControle.setBorder(null);
        txtNControle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNControleKeyTyped(evt);
            }
        });

        txtNomeControle.setBackground(new java.awt.Color(153, 153, 153));
        txtNomeControle.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txtNomeControle.setForeground(new java.awt.Color(255, 255, 255));
        txtNomeControle.setBorder(null);
        txtNomeControle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNomeControleKeyTyped(evt);
            }
        });

        lblFechar.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblFechar.setForeground(new java.awt.Color(255, 255, 255));
        lblFechar.setText("X");
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPesquisaCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                    .addComponent(txtPesquisaNome))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNControle, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(txtNomeControle))
                .addGap(18, 18, 18)
                .addComponent(lblFechar)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAtualizar)
                        .addComponent(txtNControle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblFechar)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnDeletar)
                        .addComponent(txtNomeControle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPesquisaCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaNomeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaNomeKeyTyped
        // Pesquisa pelo Nome
        
        String sql = "SELECT * FROM tb_cadastro where nome LIKE '%" 
                + txtPesquisaNome.getText() + "%' or sobrenome LIKE '%" 
                + txtPesquisaNome.getText()
                + "%' ORDER BY id_tb_cadastro DESC";
        this.preecheerJtable(sql);
    }//GEN-LAST:event_txtPesquisaNomeKeyTyped

    private void txtPesquisaCPFKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaCPFKeyTyped
        // Pesquisa pelo CPF
        String sql = "SELECT * FROM tb_cadastro where CPF LIKE '%" 
                + txtPesquisaCPF.getText() + "%' ORDER BY id_tb_cadastro DESC";
        this.preecheerJtable(sql);
    }//GEN-LAST:event_txtPesquisaCPFKeyTyped

    private void btnAtualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtualizarMouseEntered
        btnAtualizar.setBackground(Color.red);
    }//GEN-LAST:event_btnAtualizarMouseEntered

    private void btnAtualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtualizarMouseExited
        btnAtualizar.setBackground(new Color(102, 153, 255));
    }//GEN-LAST:event_btnAtualizarMouseExited

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // abrir a tela FrmAtualizarCadastro
        if(txtNControle.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Não foi selecionado a linha para tualiar os dados");
        }
        else{
            // chamar o FrmAtualizarCadastro
            FrmAtualizarCadastro frmat = new FrmAtualizarCadastro();
            frmat.setVisible(true);
            CadastroCliente.id_tb_cadastro = Integer.parseInt(txtNControle.getText());
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnDeletarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletarMouseEntered
        btnDeletar.setBackground(Color.red);
    }//GEN-LAST:event_btnDeletarMouseEntered

    private void btnDeletarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeletarMouseExited
        btnDeletar.setBackground(new Color(102, 153, 255));
    }//GEN-LAST:event_btnDeletarMouseExited

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        // Deletar a linha escolhida na Jtable
        if (txtNControle.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Nenhum item selecionado para deletar!");
        }
        else{
            CadastroCliente.id_tb_cadastro = Integer.parseInt(txtNControle.getText());
            
            int respostaJoptionPane = JOptionPane.OK_CANCEL_OPTION;
            respostaJoptionPane = JOptionPane.showConfirmDialog(null, "Deseja realmente apagar esse cadastro?", "Apagar cadastro", respostaJoptionPane);
            if (respostaJoptionPane == JOptionPane.OK_OPTION) {
                deletarLinhaDados(); // Metodo para apagar
                JOptionPane.showMessageDialog(null, "Cadastro Deletado com sucesso!");
                
            txtNControle.setText("");
            txtNomeControle.setText("");
            
               
            }
        }
        
    }//GEN-LAST:event_btnDeletarActionPerformed

    // metodo para deletar a linha e consequentimente os dados escolhidos no banco de dados
    public void deletarLinhaDados(){
        conn = Conexao.getConnection();//conecta ao banco de dados
        
        String sql = "DELETE FROM  tb_cadastro " +
                     "WHERE id_tb_cadastro = ?;";
        
        PreparedStatement stmt = null;
        
        try {
            stmt = conn.prepareStatement(sql);
            stmt.setInt(1, CadastroCliente.id_tb_cadastro);
            stmt.executeUpdate();
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Não foi possível deletar o registro do banco de dados\nErro: " + ex);
        }
    }
    
    private void txtNControleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNControleKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNControleKeyTyped

    private void txtNomeControleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeControleKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeControleKeyTyped

    private void jtableCadastroClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableCadastroClienteMouseClicked
        // Passar os valores da Jtable para os textFilds
        
        int linha = jtableCadastroCliente.getSelectedRow();//selecionar a linha e jgar na variavel linha
        txtNControle.setText(jtableCadastroCliente.getValueAt(linha, 7).toString());
        txtNomeControle.setText(jtableCadastroCliente.getValueAt(linha, 1).toString());
        
        
    }//GEN-LAST:event_jtableCadastroClienteMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // atualiza as informações da Jtable:
        String sql = "SELECT * FROM tb_cadastro ORDER BY id_tb_cadastro DESC";
        preecheerJtable(sql);
    }//GEN-LAST:event_formWindowActivated

    private void lblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseClicked
        // Fechar a aplicação quando clicar o mouse
        this.dispose();
    }//GEN-LAST:event_lblFecharMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMostrarCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMostrarCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMostrarCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMostrarCadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMostrarCadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtableCadastroCliente;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JTextField txtNControle;
    private javax.swing.JTextField txtNomeControle;
    private javax.swing.JTextField txtPesquisaCPF;
    private javax.swing.JTextField txtPesquisaNome;
    // End of variables declaration//GEN-END:variables
}
